version: "3.8"
services:
  oracle-xe:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: "123"
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data:
