services:
  oracle-xe:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "123"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
